site_name: Flight Project Docs
site_description: Documentation for the Flight Project – a microservices-based system
site_author: Your Name

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: green        # Light mode navbar color
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black        # Dark mode navbar color
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections   # Expandable sections in nav
    - navigation.expand     # Auto expand active nav
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.tooltips
    - announce.dismiss

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/your-repo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-profile

nav:
  - About: index.md
  - Architecture:
      - System Architecture: architecture.md
      - Database Diagram: database.md
      - Sequential Diagram: sequence-diagram.md
  - Setup:
      - Flights Service Setup: services/flights/setup.md
      - Booking Service Setup: services/booking/setup.md
      - Auth Service Setup: services/auth/setup.md
      - Notification Service Setup: services/notification/setup.md
  - Services:
      - Flights Service:
          - About: services/flights/index.md
          - APIs: services/flights/apis.md
      - Booking Service:
          - About: services/booking/index.md
          - APIs: services/booking/apis.md
      - Auth Service:
          - About: services/auth/index.md
          - APIs: services/auth/apis.md
      - Notification Service:
          - About: services/notification/index.md
          - APIs: services/notification/apis.md
  - APIs:
      - Overview: apis/overview.md
      - Service Based APIs: apis/service-apis.md
      - Explained APIs: apis/explained.md
  - References: references.md
  - Engineering Problems: engineering.md
